export const trackerColumns = [
  "Lead ID",
  "Company/Brand",
  "Category",
  "First Name",
  "Last Name",
  "Email Address",
  "Phone Number",
  "Owner",
  "Connected Inbox",
  "Gmail Thread ID",
  "Email Subject",
  "First Reply Date",
  "Last Reply From",
  "Last Reply Snippet",
  "Thread Message Count",
  "Email Summary",
  "Interest Signal",
  "Suggested Next Step",
  "Email Status",
  "Email Outcome",
  "Email Notes",
  "Next Action",
  "Next Action Date",
  "Overall Stage",
  "Priority",
  "Last Touch Date",
  "Dashboard URL",
  "Last Synced At",
  "Sync Source",
] as const;

export const emailThreadColumns = [
  "Lead ID",
  "Gmail Message ID",
  "Gmail Thread ID",
  "Direction",
  "From",
  "To",
  "Date",
  "Subject",
  "Body Text",
  "Snippet",
  "Has Attachments",
] as const;

export const systemColumns = [
  "Gmail Account Email",
  "Refresh Token Encrypted",
  "History Cursor",
  "Watch Expiration",
  "Last Synced At",
] as const;

